### ISSUE TITLE
terminating with  No such file or directory

### ISSUE THREAD

**Issue by hyperknot** [goldmann/docker-squash#107] opened 2016-07-21 16:40 UTC
OS X: version 10.11.5
Docker for Mac: version: mac-v1.12.0-beta20
version: 1.12.0-rc4

full log here: http://paste.ee/r/DQv68

**Comment by goldmann** [comment] 2016-07-21 18:48
This tool wasn't tested on OSX, but let's see... Can you please run a build with the verbose option (`-v`) turned on? Please do not cut the output, if possible.

**Comment by hyperknot** [comment] 2016-07-22 10:23
Here is the full log, on git master:
https://gist.github.com/hyperknot/c1b9663ad8502c4f81435c8f3a4a1d6b

I believe the problem is that cleaning up is done too early.

**Comment by goldmann** [comment] 2016-07-22 10:31
Nah, that's not the problem, if you do not run it with`-d` - we clean it up for you on error or keyboard interrupt, etc. Run it with `-d` please. This should possible give us more info. When it fails, please ls what's in the "old" directory.

We need to work on a reproducer, this looks like a weird thing. Probably related to OSX's Python, maybe PAX format?

**Comment by hyperknot** [comment] 2016-07-22 10:44
I'm not using OSX's Python, but "normal" Python from brew, 2.7.12.

I believe the bug has to be with symlinking. The missing file is:
/var/folders/h1/s_kzvc_1373c2_364k5d95980000gn/T/docker-squash-TXaMdu/old/519af099c2a839b723c68713431e4a38780ddac5e8a5c9dc28873f963d6a9149/layer.tar
it is a symlink to:
```
layer.tar -> ../../9213eb5ee2ca53c5b475d7a5fbbad6bbda3217eea7fe78a5f94998ec136dcab9/layer.tar
```

But the actual file would only need `../912...`, not double `../../912...`.

**Comment by goldmann** [comment] 2016-07-22 11:13
Oh, wait a sec. This is the tar structure, not the files inside of the image. Interesting, because we just unpack the tar we get from Docker.

**Comment by goldmann** [comment] 2016-07-22 11:18
Can you post the full directory tree in the docker-squash temporary directory? Other thing to note is that the tool wasn't tested with Docker 1.12, which could introduce some changes to the way layers are stored inside of the exported archive, again...

**Comment by hyperknot** [comment] 2016-07-22 13:12
Here is the output of ls -lR
https://gist.github.com/hyperknot/6ec3b033c66bbba5a1794b854faed11c

**Comment by goldmann** [comment] 2016-07-22 13:22
Thanks, this is more than weird... I need to poke around why we see something like this. Maybe it's a bug in RC4?

**Comment by hyperknot** [comment] 2016-07-22 13:24
No idea, I haven't tried any other version (nor I have the option to install with Docker for Mac)

**Comment by goldmann** [comment] 2016-07-25 08:12
I've run our integration tests with 1.12.0-rc4 and it worked.

**Comment by goldmann** [comment] 2016-07-25 09:52
Maybe this code is related to the issue we see: https://github.com/docker/docker/blob/v1.12.0-rc4/image/tarexport/save.go#L309-L314

**Comment by goldmann** [comment] 2016-07-25 09:54
And this commit specifically: https://github.com/docker/docker/commit/88cb79d40010d95cdbd69bb069b4726611831b27

**Comment by goldmann** [comment] 2016-07-25 09:58
And there we go - its already reported upstream: https://github.com/docker/docker/issues/24951

**Comment by hyperknot** [comment] 2016-07-25 10:05
Great find, hopefully it'll be resolved upstream!

**Comment by goldmann** [comment] 2016-07-26 10:22
Upstream issue was fixed, I'm closing this one too.

**Closed by goldmann** 2016-07-26 10:22 UTC
Labels: bug, upstream

**Comment by hyperknot** [comment] 2016-07-29 12:50
Fixed in 12 final

**Comment by goldmann** [comment] 2016-07-29 13:05
Awesome, thanks for letting me know!
