### ISSUE TITLE
ApplyLayer duplicates of file paths not supported stdout

### ISSUE THREAD

**Issue by ignatenkobrain** [goldmann/docker-squash#118] opened 2016-08-25 16:35 UTC
```
[brain@x1carbon ci-dnf-stack]$ sudo docker-squash -f 9f3214306ced c5ff8b10acc5
2016-08-25 18:33:53,904 root         INFO     docker-squash version 1.0.1, Docker 8ea583f/1.12.1, API 1.24...
2016-08-25 18:33:53,905 root         INFO     Using v2 image format
2016-08-25 18:33:53,923 root         INFO     Old image has 18 layers
2016-08-25 18:33:53,926 root         INFO     Checking if squashing is necessary...
2016-08-25 18:33:53,926 root         INFO     Attempting to squash last 15 layers...
2016-08-25 18:33:53,927 root         INFO     Saving image sha256:c5ff8b10acc50654e1855887b930bc6d891e5e72e83a849fcbccf753adf93423 to /tmp/docker-squash-g79bt4ss/old/image.tar file...
2016-08-25 18:34:21,982 root         INFO     Image saved!
2016-08-25 18:34:21,982 root         INFO     Unpacking /tmp/docker-squash-g79bt4ss/old/image.tar tar file to /tmp/docker-squash-g79bt4ss/old directory
2016-08-25 18:34:23,016 root         INFO     Archive unpacked!
2016-08-25 18:34:23,403 root         INFO     Squashing image 'c5ff8b10acc5'...
2016-08-25 18:34:23,404 root         INFO     Starting squashing...
2016-08-25 18:34:24,284 root         INFO     Squashing file '/tmp/docker-squash-g79bt4ss/old/b4f77e06062cc74e8330fb1dd63e3722dd1b8c291580b124ebb5a2d2abc562ad/layer.tar'...
2016-08-25 18:34:24,285 root         INFO     Squashing file '/tmp/docker-squash-g79bt4ss/old/8fd9d25f3ad94e845899028ea7082a98ba062fd05cc0bfa5c482e9213e5b17b3/layer.tar'...
2016-08-25 18:34:24,286 root         INFO     Squashing file '/tmp/docker-squash-g79bt4ss/old/6ee9a76bb3faaf1949ca707e475f35da947f204a1573e43a6f870f4ab318189e/layer.tar'...
2016-08-25 18:34:24,304 root         INFO     Squashing file '/tmp/docker-squash-g79bt4ss/old/ce1409e6d8e3ed4bad588ac3a85541f49cf5d05e9d2e48f46475c135c41e46f7/layer.tar'...
2016-08-25 18:34:24,350 root         INFO     Squashing file '/tmp/docker-squash-g79bt4ss/old/faec5367e879f37dfb802f6e659f9e17a68ab81fd1682aac646f5e7cf879a5a7/layer.tar'...
2016-08-25 18:34:24,352 root         INFO     Squashing file '/tmp/docker-squash-g79bt4ss/old/4b015a0c43a7d321d0aa3165ce2ac0ea2ce02ba1e3e4c54f9c22208181a1e4d0/layer.tar'...
2016-08-25 18:34:24,363 root         INFO     Squashing file '/tmp/docker-squash-g79bt4ss/old/10943c2db22c34a25cb50988549a9b498d07ad6e3f9b07b8b1aa0d3b923a3558/layer.tar'...
2016-08-25 18:34:24,412 root         INFO     Squashing file '/tmp/docker-squash-g79bt4ss/old/6e4c4ff1cee301378e89aed98dc9236fa0fcacdc38550145d525b87029c75382/layer.tar'...
2016-08-25 18:34:24,412 root         INFO     Squashing file '/tmp/docker-squash-g79bt4ss/old/93aa17c6b431a0a7f057e12194bef287c0b17b4d55716bf4a818421d2d8a270d/layer.tar'...
2016-08-25 18:34:27,591 root         INFO     Squashing file '/tmp/docker-squash-g79bt4ss/old/a2e2c269ac1996f249a02c864e0f065489fb5a76e0bb76b49271119ef2600ab0/layer.tar'...
2016-08-25 18:34:27,598 root         INFO     Squashing file '/tmp/docker-squash-g79bt4ss/old/8a8248464f93a83e6ce2c9c456a9502169fef1845903fe738ef9e170b3a9c2b5/layer.tar'...
2016-08-25 18:34:30,023 root         INFO     Squashing file '/tmp/docker-squash-g79bt4ss/old/4aab5e48c97ae45cb049419b1b97641ebc8cbc31aca52cf58bd9486f3c317437/layer.tar'...
2016-08-25 18:34:36,933 root         INFO     Squashing file '/tmp/docker-squash-g79bt4ss/old/e37a1860570c7edf4f640a251ddd757b26dd3e28797955a5fcf99d2aac5e4f72/layer.tar'...
2016-08-25 18:34:36,940 root         INFO     Squashing file '/tmp/docker-squash-g79bt4ss/old/3b7953c1be4bc7cdd5fda13a23811d8dacd22434192fe62a179e76e4ab4ba510/layer.tar'...
2016-08-25 18:34:42,933 root         INFO     Squashing finished!
2016-08-25 18:34:46,329 root         INFO     New squashed image ID is 50b2d9bde7b2295beabae4fe0cb4b555ac2a0d7a6d2d4b8c607d71c872c8c6a4
2016-08-25 18:35:01,832 root         ERROR    500 Server Error: Internal Server Error ("b'{"message":"ApplyLayer duplicates of file paths not supported stdout: {\\"layerSize\\":511219529}\\n stderr: "}'")
2016-08-25 18:35:01,832 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!
```

**Comment by goldmann** [comment] 2016-08-25 16:38
Please run it with `-v` switch to enable debug log. Additionally I would need the Dockerfile if possible and information which is the layer you want to squash.

**Comment by goldmann** [comment] 2016-08-25 16:39
Oh, and btw - please try version 1.0.2 which was released today.

**Comment by ignatenkobrain** [comment] 2016-08-25 16:43
With `-v`: https://ignatenkobrain.fedorapeople.org/squash.log
Dockerfile: https://github.com/rpm-software-management/ci-dnf-stack/blob/master/Dockerfile

**Comment by goldmann** [comment] 2016-08-25 16:46
Alright, I'll take a look at this tomorrow. At the first glance I see that we have to do with many hard links. Give 1.0.2 a shot.

**Comment by ignatenkobrain** [comment] 2016-08-25 16:57
@goldmann 1.0.2 has same problem. squash.log on fedorapeople is updated.

**Comment by goldmann** [comment] 2016-08-26 08:26
I need some more information. I cannot build the image linked above because the `rpms/` directory is empty. How should I populate it? When I skip that line (and next one which tries to install these packages) - I can build and squash this image.

I would need two things:

1. How to add these rpms?
2. What layer you want to squash from?

**Comment by goldmann** [comment] 2016-08-26 08:40
I do see also that you use Docker 1.12.1 - I haven't tested this tool on this Docker version yet, but I do not expect any issues on this side.

**Comment by ignatenkobrain** [comment] 2016-08-26 08:43
> How to add these rpms?

curl --silent http://ci.dnf.baseurl.org/job/nightly-fedora-24-x86_64/lastStableBuild/consoleText | grep "^https://copr.*\.rpm" | xargs wget

> What layer you want to squash from?

I tired to squash from that layer which has `ENV LANG C`

**Comment by goldmann** [comment] 2016-08-26 08:47
Thanks! Now I can reproduce this issue. Working on a fix.

**Comment by goldmann** [comment] 2016-08-26 09:16
Below is the list of files with duplicate entries:

```
      2 usr/lib/python3.5/site-packages/dnf/cli/commands/__pycache__/autoremove.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/commands/__pycache__/clean.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/commands/__pycache__/distrosync.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/commands/__pycache__/downgrade.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/commands/__pycache__/install.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/commands/__pycache__/makecache.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/commands/__pycache__/mark.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/commands/__pycache__/remove.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/commands/__pycache__/repolist.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/commands/__pycache__/search.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/commands/__pycache__/upgrade.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/commands/__pycache__/upgradeto.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/__pycache__/completion_helper.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/__pycache__/demand.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/__pycache__/format.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/__pycache__/__init__.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/__pycache__/main.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/__pycache__/option_parser.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/__pycache__/progress.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/cli/__pycache__/utils.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/conf/__pycache__/__init__.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/conf/__pycache__/parser.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/conf/__pycache__/read.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/conf/__pycache__/substitutions.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/callback.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/comps.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/const.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/crypto.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/drpm.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/exceptions.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/i18n.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/__init__.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/lock.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/match_counter.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/package.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/persistor.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/plugin.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/pycomp.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/repodict.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/sack.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/selector.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/subject.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/transaction.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/__pycache__/util.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/rpm/__pycache__/connection.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/rpm/__pycache__/error.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/rpm/__pycache__/__init__.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/rpm/__pycache__/miscutils.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/rpm/__pycache__/transaction.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/yum/__pycache__/__init__.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/yum/__pycache__/misc.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/yum/__pycache__/packages.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/yum/__pycache__/rpmtrans.cpython-35.pyc
      2 usr/lib/python3.5/site-packages/dnf/yum/__pycache__/sqlutils.cpython-35.pyc
```

First column indicates how many times it was found in the layer archive.

**Comment by ignatenkobrain** [comment] 2016-08-26 09:18
@goldmann what do you mean by duplicates? Actually when you do `dnf -y update` it updates `python3-dnf`, then you do `dnf -y install /rpms/*.rpm` and it updates it once more.

**Comment by goldmann** [comment] 2016-08-26 09:20
After squashing files above were added to tar archive twice which is the cause of this issue. Now I need to figure out why it happened and what to fix. It has nothing to do with the way you install / remove files.

**Comment by goldmann** [comment] 2016-08-26 10:53
Found the issue. It's exactly described in the `TODO` here: https://github.com/goldmann/docker-squash/blob/11b60098c5d8efddb89906d1cb5c3a9f55e216a8/docker_squash/image.py#L571

We indeed need to check other layers. In your example we do have same files in following places:

* Base image
* Files updated in some squashed layers (`yum update`)
* Files updates in other layers (`yum install`)

Since we did not check other layers (these which contain updated files) - we add them blindly back which is bad. Working on a smaller reproducer and a fix.

**Comment by goldmann** [comment] 2016-08-26 11:15
Just to clarify it even more - this issue exists only if you add **in several layers** to be squashed both - the file **and** a hard link to it under same name. This is true in this example because we upgrade whole system (`python3-dnf` is updated as part of it), but later we install an even newer version of if with `dnf install`.

**Comment by goldmann** [comment] 2016-08-26 12:33
Can you please give `gh-118-duplicate-hard-link` branch a shot?

```
pip install -U --user https://github.com/goldmann/docker-squash/archive/gh-118-duplicate-hard-link.zip
```

**Comment by ignatenkobrain** [comment] 2016-08-26 13:03
@goldmann I don't use pip, but I tested it and it fixes problem. But actually looks like it broke something. Squashing finished correctly, but after I was not able to squash with the same parameters.

```
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'{"message":"file integrity checksum failed for \\"usr/lib/locale/locale-archive\\""}'")
```

**Comment by goldmann** [comment] 2016-08-26 13:17
What do you mean by "but after I was not able to squash with the same parameters"?

**Comment by goldmann** [comment] 2016-08-30 13:10
I'm closing this issue since a potential fix was merged. Please reopen if this happens again or open a new ticket in case of other issues.

**Closed** 2016-08-30 13:09 UTC
Labels: bug
