### ISSUE TITLE
Using new Python Docker client gives 'module' object has no attribute 'AutoVersionClient'

### ISSUE THREAD

**Issue by dustyhorizon** [goldmann/docker-squash#152] opened 2017-07-15 09:46 UTC
Latest docker-squash and docker-py returns 'module' object has no attribute 'AutoVersionClient' when run.

Any tips?

Regards.

**Comment by goldmann** [comment] 2017-07-15 09:59
Thanks, I'll look into this next week.

**Comment by goldmann** [comment] 2017-07-17 07:58
I can confirm this with `docker` client python library, version `2.4.2`.

**Comment by goldmann** [comment] 2017-07-17 08:04
It is caused by this commit: https://github.com/docker/docker-py/commit/c7903f084eb3a7525e21974390b48e2a0dc03732

**Comment by goldmann** [comment] 2017-07-17 08:12
This was fixed via #143 in master some time ago. You can use it by installing it via: `pip install --user -U https://github.com/goldmann/docker-squash/archive/master.zip`

I'll prepare a new release (`1.0.6`) soon.

Closing it.

**Closed by goldmann** 2017-07-17 08:12 UTC
