### ISSUE TITLE
Squashing hangs and times out

### ISSUE THREAD

**Issue by bparees** [goldmann/docker-squash#51] opened 2016-02-19 04:19 UTC
```
2016-02-18 22:46:36,731 root         INFO     Squashing image 'rhscl/python-34-rhel7-candidate'...
2016-02-18 22:46:36,810 root         INFO     Old image has 18 layers
2016-02-18 22:46:36,810 root         INFO     Attempting to squash from layer 2ceccd5b1bd58dfa66cc9326d5e811141b351a116f414e9ed4166bf43337c256...
2016-02-18 22:46:36,810 root         INFO     Checking if squashing is necessary...
2016-02-18 22:46:36,810 root         INFO     We have 11 layers to squash
2016-02-18 22:46:36,811 root         INFO     Saving image 4695cb8451fc1d8de3bdedf5cab2af971a464114fbb34b42a3dab535a27e446b to /tmp/docker-squash-ElGSYo/image.tar file...
2016-02-18 22:56:36,912 root         ERROR    UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/docker_scripts/squash.py", line 68, in _save_image
    image = self.docker.get_image(image_id)
  File "/root/.local/lib/python2.7/site-packages/docker_py-1.2.3-py2.7.egg/docker/utils/decorators.py", line 15, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/root/.local/lib/python2.7/site-packages/docker_py-1.2.3-py2.7.egg/docker/client.py", line 618, in get_image
    stream=True)
  File "/root/.local/lib/python2.7/site-packages/docker_py-1.2.3-py2.7.egg/docker/client.py", line 106, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
```

I see this on a machine where i'm performing a series of squashes (@mfojtik this is from our push job when it builds all the images... seems like things go ok for a while, and then something goes bad.  I've ssh'd into the machine and no squash operations work once it gets in this state, even ones the job did successfully earlier.  Restarting the docker daemon does not help, either.  Can you work with @goldmann tomorrow to see if you can figure out what's going on?  Otherwise we're going to have to disable squashing to get our images rebuilt)

I can also confirm we're not out of disk space on the machine.

**Comment by bparees** [comment] 2016-02-19 04:20
(forgot @mfojtik is travelling tomorrow.  When you get a chance I guess.  Or @goldmann if you have any immediate ideas).

i've also updated to 0.4.4, no change in behavior.

**Comment by goldmann** [comment] 2016-02-19 06:19
First idea - too many concurrent builds on the host => high CPU usage on the Docker daemon => timing out.

**Comment by mfojtik** [comment] 2016-02-19 06:20
@goldmann how about retrying when that happens?

**Comment by goldmann** [comment] 2016-02-19 06:21
If you run concurrent builds - limit it's number. Docker is not prepared for heavy load on the `save` call. 

We do have retry in place (3 times), I'll take a look.

**Comment by mfojtik** [comment] 2016-02-19 06:22
@goldmann i don't think there is concurrent build running on that node when we squash... I think we squash/build sequentially.

**Comment by goldmann** [comment] 2016-02-19 06:23
Can you get me a traceback with debug enabled from `0.4.4`?

**Comment by mfojtik** [comment] 2016-02-19 06:23
@bparees do you know when this broke? did it broke with latest docker update?

**Comment by goldmann** [comment] 2016-02-19 06:25
Try maybe also update `docker-py` to `1.6.0`. It may have troubles with new Docker. Which version it is, btw?

**Comment by mfojtik** [comment] 2016-02-19 06:27
fyi, https://ci.openshift.redhat.com/jenkins/job/push_images/18590/consoleText (search for UnixHTTPConnectionPool).

**Comment by mfojtik** [comment] 2016-02-19 06:27
@goldmann   `easy_install -q --user docker_py==1.2.3 docker-scripts==0.4.2`

**Comment by goldmann** [comment] 2016-02-19 06:31
OK, @bparees said it's the same with `0.4.4`, but please use this version, it has a lot of fixes. It should be save to use also `1.6.0` of `docker-py` - we use this version on our CI. Can you upgrade and try again?

**Comment by TomasTomecek** [comment] 2016-02-19 07:20
What is the version of docker?

**Comment by bparees** [comment] 2016-02-19 14:28
1) it does retry.  once it gets in this failure mode, it never succeeds in squashing anything again.
2) I updated to 0.4.4 and had the same result (though that was upgrading on a machine that was already in a bad state, I did not try a full run starting with 0.4.4)
3) docker is version 1.8

**Comment by goldmann** [comment] 2016-02-19 14:32
I need to replicate this locally and will get back to you. I see that this is only happens on one image, can you confirm? I see that other builds are squashed correctly. Or is it random?

**Comment by bparees** [comment] 2016-02-19 14:37
@goldmann no, what I think happens is that at some point the system gets into a bad state.  From then on, all squashing fails, regardless of image.  For example I connected to the system that log is from, and tried to re-build some of the images that earlier had succeeded+squashed correctly, and now I would get the error.

**Comment by TomasTomecek** [comment] 2016-02-19 16:11
@bparees It sounds like a worse version of https://github.com/docker/docker/issues/13885

**Comment by goldmann** [comment] 2016-02-19 16:12
In that call I'm just executing docker-py's get_image method, so I don't know what could be wrong there tbh? Have you updated to 1.6.0 as I suggested above?

**Comment by bparees** [comment] 2016-02-19 16:13
not yet.

**Comment by goldmann** [comment] 2016-02-19 16:14
Give it a shot, I don't think the issue is in my code tbh.

**Comment by TomasTomecek** [comment] 2016-02-19 16:47
I have to second @goldmann here. This indeed looks like a lock up in docker daemon (and it's super weird that restart doesn't help).

**Comment by mfojtik** [comment] 2016-02-19 20:23
if it locks really hard, youbhave to remove the socket imho.

**Comment by bparees** [comment] 2016-02-19 20:24
i've updated all our repos to use docker-py 1.6.0 and docker-scripts 0.4.4.

right now i'm rebuilding everything w/o squash just to get fresh images published.  Once that's done, i'll re-enable squashing and see what happens.

**Comment by goldmann** [comment] 2016-02-19 20:29
OK, let me know if this helped.

**Comment by goldmann** [comment] 2016-02-21 08:04
Ok, thanks for the update!

**Comment by bparees** [comment] 2016-03-04 23:38
this is failing again:

https://ci.openshift.redhat.com/jenkins/job/push_images/18905/console
```
2016-03-04 17:58:33,688 root         INFO     Running version 0.4.4, Docker 50e78a0/1.9.1, API 1.21...
2016-03-04 17:58:33,688 root         INFO     Squashing image 'rhscl/python-34-rhel7-candidate'...
2016-03-04 17:58:33,745 root         INFO     Old image has 18 layers
2016-03-04 17:58:33,745 root         INFO     Attempting to squash from layer 47c595c9e8371c009e421df21413e23489107c74d2d807c099c7e093f89ddb56...
2016-03-04 17:58:33,745 root         INFO     Checking if squashing is necessary...
2016-03-04 17:58:33,745 root         INFO     We have 11 layers to squash
2016-03-04 17:58:33,746 root         INFO     Saving image cef3db96f1ebc96ca63a19ae537d034a4b04c73b425b7e0874b09ab142c51f46 to /tmp/docker-squash-WtdUCa/image.tar file...
2016-03-04 18:08:33,847 root         ERROR    UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/docker_scripts/squash.py", line 70, in _save_image
    image = self.docker.get_image(image_id)
  File "/root/.local/lib/python2.7/site-packages/docker_py-1.6.0-py2.7.egg/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/root/.local/lib/python2.7/site-packages/docker_py-1.6.0-py2.7.egg/docker/api/image.py", line 17, in get_image
    res = self._get(self._url("/images/{0}/get", image), stream=True)
  File "/root/.local/lib/python2.7/site-packages/docker_py-1.6.0-py2.7.egg/docker/client.py", line 110, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
```

**Comment by goldmann** [comment] 2016-03-05 08:58
This is not an issue with the squashing tool. The reason for failing is that the Docker daemon was not able to deliver the saved (exported) tar archive with the image. This happens because the host where the Docker daemon (or the daemon itself) is busy. You can confirm this by looking at the daemon's log. 

What you can do is to bump the `DOCKER_TIMEOUT` env variable to wait longer for the image, or - if you think it makes sense - request adding a configurable `--retry` argument.

**Comment by bparees** [comment] 2016-03-05 13:42
This docker squash operation is the only thing running on the host.  What's the default timeout?

**Comment by goldmann** [comment] 2016-03-05 15:44
Default timeout is set to 600 seconds. There are 3 retries, which means that Docekr daemon is not able to prepare the image in half an hour.

It may be an issue with requests package too, what version do you use? `pip freeze | grep requests`

Some more (or less) related issues:

* https://github.com/docker/docker-py/issues/398 (Are you by chance running your Jenkins slave on EC2?)
* https://github.com/docker/compose/issues/1045

Home questions which could help narrow the issue:

* What is the Jenkins slave set up?
* Where it is running?
* What are the specs (CPU, RAM, disk type)?
* What storage plugin Docker uses there?
* Is this machine shared with other jobs?
* What's the load on the machine while building the image?

**Comment by bparees** [comment] 2016-03-05 17:08
> It may be an issue with requests package too, what version do you use? pip freeze | grep requests

pip is not installed.  we're using easy_install to install docker-scripts and docker_py.

> What is the Jenkins slave set up?
> Where it is running?
> What are the specs (CPU, RAM, disk type)?

the slave is an ec2 instance, m4.large

> What storage plugin Docker uses there?

storage should be the defaults (devicemapper)

> Is this machine shared with other jobs?

machine is not shared

> What's the load on the machine while building the image?

i don't have load data, sorry, but the first few squashes on the machine proceed fine, I still think something is putting the docker daemon into a bad state after repeated build/squash operations.

**Comment by bparees** [comment] 2016-03-05 17:10
given that we're only running one squash at a time, and the timeout is 30mins, it's hard to imagine we're overtaxing EBS (per the ec2 link you referenced).

**Comment by TomasTomecek** [comment] 2016-03-05 19:08
`$ docker info` could be helpful

**Comment by bparees** [comment] 2016-03-05 19:20
thanks, i always forget about that.  this is from an equivalent ec2 instance, not the exact one that hit the errors.  the build instances have a larger disk:

```
$ docker info
Containers: 3
Images: 180
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:2-50895915-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/docker-vg/docker-data
 Metadata file: /dev/docker-vg/docker-metadata
 Data Space Used: 3.43 GB
 Data Space Total: 17.18 GB
 Data Space Available: 13.75 GB
 Metadata Space Used: 6.57 MB
 Metadata Space Total: 1.074 GB
 Metadata Space Available: 1.067 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
CPUs: 2
Total Memory: 7.389 GiB
Name: ip-172-18-9-254.ec2.internal
ID: KBFV:ZDWQ:HMXI:2K5S:ESGU:HKFC:B4MM:43ZX:4L4I:V5EW:F2M5:7TIR
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by goldmann** [comment] 2016-03-05 19:57
> given that we're only running one squash at a time, and the timeout is 30mins, it's hard to imagine we're overtaxing EBS (per the ec2 link you referenced).

It needs some investigation, because the `save` call works in following way:

1. Files from each layer are saved in a temporary directory (IIRC the default is: `/var/lib/docker/tmp`, can be changed by setting `DOCKER_TMPDIR`)
2. All layers are tarred.
3. All tars are tarred into the export tar.
4. Tar is sent to the client (`docker-scripts`)

It means that even if the call timeouts - files are saved (sometimes 3 times before it fails) to the tmp directory. Looking at (probably debug level) Docker logs should help here to determine what's going on.

After the save call is executed, docker scripts unpacks the tarball (again, disk operation), reads all layers to squash and copy files over to new tar (yep, disk operation) and loads the image into Docker (again - disk). Whole process makes disks pretty hot.

To help you out, we need details about the instance, `m4.large` is not enough. What kind of EBS storage is backing up it? 	EBS General Purpose (SSD)?	EBS Provisioned IOPS (SSD)?	EBS Magnetic? I think default for your instance is EBS General Purpose (SSD) - what disk size it is? It gets 3 IOPS per GB, so if the disk is 10 GB you get 30 IOPS.

Since I still think it's a resource issue, I recommend following:

1. Use some tool to monitor IO, like `iostat`
2. Check out Docker daemon log around the time when the build is failing
3. Play with IOPS settings for the instance
4. Try other instance (instead EBS optimized - use SSD, `m3.large`?)
5. Maybe try to create a ramdisk (if you have enough) RAM and provide it to Docker as `DOCKER_TMPDIR`

**Comment by goldmann** [comment] 2016-03-05 20:18
Probably `r3.large` would be a better choice, for almost the same price.

Additionally, your instance's storage bandwidth is maxing at 56.25 MB/s. Which doesn't sound that bad, but as always - it's max you can get, so normally you get much slower speeds. And on top of this is the IOPS limitation (there are really many files to write, several times). I forgot to add that Docker itself unpacks layers on import. You can assume that an image is read/wrote ~3 times before it'll be available as squashed image in Docker daemon.

I just found an [interesting report](https://s3.amazonaws.com/cloudharmony/block-storage_1_0/aws:ec2/m4.large/ebs/us-east-1/2015-06-28/5140/626128-1/report.pdf) for your instance's size storage. Quick stats: throughput at 17MB/s, IOPS ~400 with 128GB disk (remember 3 IOPS per GB limit? 3x128 = 384). I suspect you have quite big iowait on your host.

You could also give `fio` a shot, here are numbers from my laptop (SSD):

```
$ fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=test --bs=4k --iodepth=64 --size=1G --readwrite=randrw --rwmixread=75
test: (g=0): rw=randrw, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=64
fio-2.2.8
Starting 1 process
test: Laying out IO file(s) (1 file(s) / 1024MB)
Jobs: 1 (f=1): [m(1)] [100.0% done] [101.3MB/34585KB/0KB /s] [25.1K/8646/0 iops] [eta 00m:00s]
test: (groupid=0, jobs=1): err= 0: pid=16553: Sat Mar  5 21:12:46 2016
  read : io=784996KB, bw=99695KB/s, iops=24923, runt=  7874msec
  write: io=263580KB, bw=33475KB/s, iops=8368, runt=  7874msec
  cpu          : usr=3.91%, sys=91.10%, ctx=7443, majf=0, minf=8
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued    : total=r=196249/w=65895/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
   READ: io=784996KB, aggrb=99694KB/s, minb=99694KB/s, maxb=99694KB/s, mint=7874msec, maxt=7874msec
  WRITE: io=263580KB, aggrb=33474KB/s, minb=33474KB/s, maxb=33474KB/s, mint=7874msec, maxt=7874msec

Disk stats (read/write):
    dm-2: ios=191205/64272, merge=0/0, ticks=97462/17169, in_queue=114761, util=97.53%, aggrios=196091/65905, aggrmerge=181/65, aggrticks=98896/17457, aggrin_queue=116204, aggrutil=96.72%
  sda: ios=196091/65905, merge=181/65, ticks=98896/17457, in_queue=116204, util=96.72%
```

**Comment by TomasTomecek** [comment] 2016-03-05 21:35
It looks okay except for:
```
Backing Filesystem: 
```
Kind of funny, that it doesn't say anything. It could be interesting to change graph driver to `overlay` and see if it's reproducible (I've seen some docker issue (lock up: https://github.com/docker/docker/issues/13885#issuecomment-191148608, https://github.com/docker/docker/issues/13885#issuecomment-191318790) which turned out to be a devicemapper issue).

**Comment by bparees** [comment] 2016-03-05 22:57
yeah it's general purpose ssd and it's 50gigs.

will have to dig into the other items later (turns out it's a c4.large not m4.large, sorry)

**Comment by goldmann** [comment] 2016-03-06 11:41
I've run a c4.large instance myself, installed Docker and tried to squash the `jboss/wildfly` image about 50 times, sequentially. It worked.

@TomasTomecek made a good point about the storage, my output is following (fully updated RHEL 7.2, with latest Docker from extras repo: `docker-1.8.2-10.el7.x86_64`):

```
$ docker info
Containers: 0
Images: 78
Storage Driver: devicemapper
 Pool Name: docker-202:2-192938227-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 24.86 GB
 Data Space Total: 107.4 GB
 Data Space Available: 24.77 GB
 Metadata Space Used: 15.83 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.132 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: Employee SKU
CPUs: 2
Total Memory: 3.518 GiB
Name: ip-172-30-0-58.eu-west-1.compute.internal
ID: F6RV:OX76:YSMX:AQPE:RHCX:7U2Y:USEL:EKJ2:AWX5:OZ6W:XFWE:VKBF
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by goldmann** [comment] 2016-05-23 12:46
We didn't get much further with it, but I'm closing it again. Let's have another round when it happens again.

**Closed by goldmann** 2016-05-23 12:46 UTC

**Comment by rudyzhou2** [comment] 2016-06-23 06:01
Also experienced this issue on a rather large container image with docker running on local disk, is there anyway to increase the default timeout limit?

Cheers,

Rudy
