### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 4: invalid start byte

### ISSUE THREAD

**Issue by gcstang** [goldmann/docker-squash#76] opened 2016-04-01 15:37 UTC
I see this error when running:
docker-squash -v -t squash --output-path image.tar <myhostname>:5000/apache

UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 4: invalid start byte

This image was created previously and and pushed to my private registry then pulled back into my local docker images.

Running version 1.0.0rc3
OSX El Capitan
Docker version 1.10.3, build 20f81dd
docker history <myhostname>:5000/apache
Image History:

```
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT

f20224ea3037        3 days ago          /bin/sh -c #(nop) CMD ["/run-httpd.sh"]         0 B
<missing>           3 days ago          /bin/sh -c #(nop) EXPOSE 8080/tcp 8443/tcp      0 B
<missing>           3 days ago          /bin/sh -c /bin/bash -c 'source $HOME/.bashrc   14 MB
<missing>           3 days ago          /bin/sh -c ansible-playbook site.yml -c local   104.3 MB
<missing>           3 days ago          /bin/sh -c #(nop) WORKDIR /ansible              0 B
<missing>           3 days ago          /bin/sh -c #(nop) ADD dir:7248510a4752d37b13b   1.492 MB
<missing>           3 days ago          /bin/sh -c /bin/bash -c 'source $HOME/.bashrc   27.25 MB
<missing>           3 days ago          /bin/sh -c /bin/bash -c 'source $HOME/.bashrc   3.18 MB
<missing>           3 days ago          /bin/sh -c yum -y install PyYAML python-httpl   112.2 MB
<missing>           3 days ago          /bin/sh -c /bin/bash -c 'source $HOME/.bashrc   11.92 MB
<missing>           3 days ago          /bin/sh -c yum -y install wget                  459.5 MB
<missing>           3 days ago          /bin/sh -c #(nop) ENV TERM=xterm-256color       0 B
<missing>           3 days ago          /bin/sh -c #(nop) ENV no_proxy=*.us.oracle.co   0 B
<missing>           3 days ago          /bin/sh -c #(nop) ENV https_proxy=http://rmdc   0 B
<missing>           3 days ago          /bin/sh -c #(nop) ENV http_proxy=http://rmdc-   0 B
<missing>           3 days ago          /bin/sh -c #(nop) LABEL Version=15.1.0          0 B
<missing>           3 days ago          /bin/sh -c #(nop) LABEL License=Oracle          0 B
<missing>           3 days ago          /bin/sh -c #(nop) LABEL Description=Oracle Op   0 B
<missing>           3 days ago          /bin/sh -c #(nop) MAINTAINER Gil Collins, gil   0 B
<missing>           4 weeks ago         /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B
<missing>           4 weeks ago         /bin/sh -c #(nop) ADD file:4ecf2d36b14b9320c8   205.9 MB
<missing>           11 months ago       /bin/sh -c #(nop) MAINTAINER Oracle Linux Pro   0 B
```

**Comment by goldmann** [comment] 2016-04-01 15:58
Can you please paste full log?

**Comment by gcstang** [comment] 2016-04-01 20:11
Added full log
[dockersquashlogrc3.txt](https://github.com/goldmann/docker-squash/files/200275/dockersquashlogrc3.txt)

**Comment by goldmann** [comment] 2016-04-01 21:17
Thanks, I'll need to work on a reproducer so I can fix it properly. I'll try to come up with something next week.

**Comment by goldmann** [comment] 2016-04-04 09:47
I think I found the issue, stay tuned.

**Comment by goldmann** [comment] 2016-04-04 09:57
Please use the `gh-76-pax-unicode` branch, try this:

```
pip install -U --user https://github.com/goldmann/docker-squash/archive/gh-76-pax-unicode.zip
```

...and re-run the build so I can see if this fixed it.

**Comment by gcstang** [comment] 2016-04-04 13:23
Worked!  Thank you very much!

Is there a way to pipe it through the process instead of saving it to a temp tar on disk and loading it?

**Comment by goldmann** [comment] 2016-04-04 13:30
Good news!

This was how it was done before. The problem is that piping means that the whole tar image is put into memory. To be fair - this is also the case with storing/reading from the disk currently, but this will most likely change before `1.0.0`.

In general - I had more requests to do it via disk to save memory, since this could kill the squash when we run multiple in parallel. We would just run out memory. See https://github.com/goldmann/docker-squash/issues/29

On the other side - there is no real benefit in speed when doing it entirely in RAM. I've done some performance tests before I switched to disk.

P.S. @hjc1710 volunteered to look at reading/sending the image in chunks. This would fix the out of memory issues for disk stored tar archives.

**Comment by goldmann** [comment] 2016-04-04 13:31
I merged the change and I'm closing this issue. Feel free to continue the piping talk in #29.

**Closed** 2016-04-04 13:30 UTC
