### ISSUE TITLE
Squash with no tag argument causes NoneType exception

### ISSUE THREAD

**Issue by Firstyear** [goldmann/docker-squash#85] opened 2016-04-08 05:39 UTC
I had to remove some exception wrappers but:

```
2016-04-08 15:35:05,179 root         INFO     docker-squash version 1.0.0rc3, Docker c6607d2/1.9.1, API 1.21...
2016-04-08 15:35:05,180 root         INFO     Using v1 image format
None
Traceback (most recent call last):
  File "/bin/docker-squash", line 9, in <module>
    load_entry_point('docker-squash==1.0.0rc3', 'console_scripts', 'docker-squash')()
  File "/usr/lib/python2.7/site-packages/docker_squash/cli.py", line 82, in run
    cli.run()
  File "/usr/lib/python2.7/site-packages/docker_squash/cli.py", line 63, in run
    from_layer=args.from_layer, tag=args.tag, output_path=args.output_path, tmp_dir=args.tmp_dir, development=args.development).run()
  File "/usr/lib/python2.7/site-packages/docker_squash/squash.py", line 61, in run
    return self.squash(image)
  File "/usr/lib/python2.7/site-packages/docker_squash/squash.py", line 73, in squash
    new_image_id = image.squash()
  File "/usr/lib/python2.7/site-packages/docker_squash/image.py", line 66, in squash
    self._before_squashing()
  File "/usr/lib/python2.7/site-packages/docker_squash/v1_image.py", line 24, in _before_squashing
    super(V1Image, self)._before_squashing()
  File "/usr/lib/python2.7/site-packages/docker_squash/image.py", line 143, in _before_squashing
    self.image_name, self.image_tag = self._parse_image_name(self.tag)
  File "/usr/lib/python2.7/site-packages/docker_squash/image.py", line 356, in _parse_image_name
    if ':' in image and '/' not in image.split(':')[-1]:
TypeError: argument of type 'NoneType' is not iterable

```

Adding a bit of printing, it looks like self.tag is set None when we reach  

```
 File "/usr/lib/python2.7/site-packages/docker_squash/image.py", line 143, in _before_squashing
    self.image_name, self.image_tag = self._parse_image_name(self.tag)
```

This goes against the claim on the readme, as it says by default tag will be set to image name.

**Comment by Firstyear** [comment] 2016-04-08 05:39
work around, is to run

docker-squash -t imagename imagename

**Comment by goldmann** [comment] 2016-04-08 07:27
Thanks for report.

This is a duplicate of #66 which is already solved in master. It'll be part of 1.0.0rc4 release (hopefully today), but you are free to use master.

Closing.

**Closed by goldmann** 2016-04-08 07:27 UTC
