### ISSUE TITLE
404 Client Error: Not Found ("open /var/lib/docker/tmp/docker-import-016911253/boot/json: no such file or directory")

### ISSUE THREAD

**Issue by gcstang** [goldmann/docker-squash#87] opened 2016-04-20 18:49 UTC
[dsquash04202016.txt](https://github.com/goldmann/docker-squash/files/228615/dsquash04202016.txt)

New one seems to go well until it tried to import the squashed image, all in the log.

```
Squashing finished!
2016-04-20 13:32:36,192 root         INFO     New squashed image ID is ad783803e6da683f2799bab0e24ca1a0e0cfbbcac37cb95d076611678ef4251b
2016-04-20 13:32:36,194 root         DEBUG    Generating tar archive for the squashed image...
2016-04-20 13:34:14,103 root         DEBUG    Archive generated
2016-04-20 13:34:14,123 root         DEBUG    Loading squashed image...
2016-04-20 13:37:12,402 requests.packages.urllib3.connectionpool DEBUG    "POST /v1.23/images/load HTTP/1.1" 404 86
2016-04-20 13:37:12,404 root         DEBUG    Cleaning up /var/folders/5h/y__gjs8s3w30g7jvkjth1l8h0000gn/T/docker-squash-qaO041 temporary directory
2016-04-20 13:37:14,257 root         ERROR    404 Client Error: Not Found ("open /var/lib/docker/tmp/docker-import-016911253/boot/json: no such file or directory")
```

**Comment by goldmann** [comment] 2016-04-21 10:48
Which version it is? What revision you used?

**Comment by goldmann** [comment] 2016-04-21 10:53
I see that you use Docker 1.11.x. Can you try downgrade Docker to 1.10.x and try again?

**Comment by goldmann** [comment] 2016-04-21 11:17
I just run our integration tests on Docker 1.11.0 and all passed, so this may be something different.

**Comment by goldmann** [comment] 2016-04-21 11:34
I found similar error on this blog post: https://arvimal.wordpress.com/2014/08/16/error-open-tmpdocker-import-repobinjson-no-such-file-or-directory/

**Comment by goldmann** [comment] 2016-04-21 11:57
Please do one excise - squash the image with `--output-path` specified. Then use that archive to load into Docker daemon: `docker load -i archive.tar` if this fails.

Other questions:

1. Can you reproduce it on other image?
2. Can you share the archive?

**Comment by gcstang** [comment] 2016-04-21 12:52
I'll give that a shot and I'm on docker-squash 1.0.0dev

**Comment by goldmann** [comment] 2016-04-21 12:54
Unfortunately `1.0.0dev` doesn't tell me anything, since this is a development version attached to master. I would need to know exact commit. Or better - use 1.0.0rc4.

**Comment by gcstang** [comment] 2016-04-21 13:00
Will do, it takes a while to run but I'll get back to you afterwards.

**Comment by gcstang** [comment] 2016-04-21 17:42
12:34 $ docker load -i oracle12csqsh.tar
072c3601d8b8: Loading layer
open /var/lib/docker/tmp/docker-import-934034371/boot/json: no such file or directory

**Comment by goldmann** [comment] 2016-04-24 15:30
For me it seems that there is a `/boot/json` file created by the build process at some stage. It could be removed later. This file could be a special file of some kind (link) and it could be added/removed in some layers. Without information how it was created/added/removed I'll not be able to fix this.

**Comment by TomasTomecek** [comment] 2016-04-26 09:23
Could it be possible that `/boot` is a special mount and all files from there are not present in the final image?

**Comment by goldmann** [comment] 2016-04-26 09:45
For me the `/boot/json` file looks suspicious, not necessary the `/boot` directory. I'm not sure what's the purpose of this file and how it was created.

**Comment by goldmann** [comment] 2016-05-23 11:41
I'm closing this issue, because I'm not able to reproduce it with the available information, nor I have access to the file that's causing troubles.

**Closed by goldmann** 2016-05-23 11:41 UTC

**Comment by mpettigr** [comment] 2016-06-11 20:12
This issue is still out there in the wild however.  I hit it also.  Unfortunately, I too don't have a reproducible config as the application I'm trying to docker contain is proprietary.

2016-06-11 14:37:43,830 root         ERROR    404 Client Error: Not Found ("open /home-local/docker/var_lib_docker/tmp/docker-import-683292478/bin/json: no such file or directory")

But here's some additional clues for the next person who files additional info with hopefully a testcase on this issue.
* docker 1.11.2
* running on CentOS 7 with /devicemapper/direct-lvm for storage option
* I soft linked /var/lib/docker to another mount for additional storage ( as indicated above ) - /home-local/docker/var_lib_docker
* The indicated path doesn't exist 2 levels above it, i.e.,  /home-local/docker/var_lib_docker/tmp/docker-import-683292478 doesn't exist.

**Comment by mpettigr** [comment] 2016-06-12 01:12
Further above you asked if using "--output-path" worked.  I tried it in my case and it does generate a tar file properly then errors out after:

2016-06-11 17:16:47,304 root         INFO     New squashed image ID is 8c523af632acee392064f851f8dc3f4e88004e98bff16654cd17a8c96a118cd6
2016-06-11 17:17:24,687 root         INFO     Image available at '/home-local/docker/output_path/test.tar'
2016-06-11 17:22:45,640 root         ERROR    404 Client Error: Not Found ("open /home-local/docker/var_lib_docker/tmp/docker-import-010117631/9fb8c6e9661e6eb12051a1fcd5f47c09cd78c23339969e5932f59835dd4e76ef/json: no such file or directory")
2016-06-11 17:22:45,640 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!
