### ISSUE TITLE
Can't squash image with docker in direct-lvm mode

### ISSUE THREAD

**Issue by Ehekatl** [goldmann/docker-squash#106] opened 2016-07-19 10:58 UTC
```
[root@ tmp]# docker-squash strikingly_base:latest
2016-07-19 10:54:21,576 root         INFO     docker-squash version 1.0.0rc7, Docker 5604cbe/1.11.1, API 1.23...
2016-07-19 10:54:21,576 root         INFO     Using v2 image format
2016-07-19 10:54:21,587 root         INFO     Old image has 11 layers
2016-07-19 10:54:21,588 root         INFO     Checking if squashing is necessary...
2016-07-19 10:54:21,588 root         INFO     Attempting to squash last 11 layers...
2016-07-19 10:54:21,588 root         INFO     Saving image sha256:ccdbae88572b4fb11fa82262001be0900f9968da96df053fbc64541ea5737df4 to /tmp/docker-squash-RR0Jnf/old/image.tar file...
2016-07-19 10:54:30,226 root         INFO     Image saved!
2016-07-19 10:54:30,226 root         INFO     Unpacking /tmp/docker-squash-RR0Jnf/old/image.tar tar file to /tmp/docker-squash-RR0Jnf/old directory
2016-07-19 10:54:30,291 root         ERROR    'TarFile' object has no attribute '__exit__'
2016-07-19 10:54:30,291 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!
```

log says image saved but actually /tmp folder is empty

**Comment by goldmann** [comment] 2016-07-19 11:01
What OS do you use? Can you run it with `-v`?

**Comment by goldmann** [comment] 2016-07-19 11:03
You cannot see the tar, because it was cleaned up when the failure occurred. You can enable `-d` flag to enter development mode and not clean after failures.

**Comment by Ehekatl** [comment] 2016-07-19 12:56
@goldmann k, now I get the `image.tar` I can untar it without problem, verbose log dump the same error, wired
```
2016-07-19 12:47:44,359 root         INFO     Image saved!
2016-07-19 12:47:44,360 root         INFO     Unpacking /tmp/docker-squash-UbsHen/old/image.tar tar file to /tmp/docker-squash-UbsHen/old directory
2016-07-19 12:47:44,361 root         ERROR    'TarFile' object has no attribute '__exit__'
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/site-packages/docker_squash/cli.py", line 62, in run
    from_layer=args.from_layer, tag=args.tag, output_path=args.output_path, tmp_dir=args.tmp_dir, development=args.development).run()
  File "/usr/local/lib/python2.6/site-packages/docker_squash/squash.py", line 58, in run
    return self.squash(image)
  File "/usr/local/lib/python2.6/site-packages/docker_squash/squash.py", line 70, in squash
    new_image_id = image.squash()
  File "/usr/local/lib/python2.6/site-packages/docker_squash/image.py", line 69, in squash
    self._before_squashing()
  File "/usr/local/lib/python2.6/site-packages/docker_squash/v2_image.py", line 15, in _before_squashing
    super(V2Image, self)._before_squashing()
  File "/usr/local/lib/python2.6/site-packages/docker_squash/image.py", line 209, in _before_squashing
    self._unpack(self.old_image_tar, self.old_image_dir)
  File "/usr/local/lib/python2.6/site-packages/docker_squash/image.py", line 351, in _unpack
    with tarfile.open(tar_file, 'r') as tar:
AttributeError: 'TarFile' object has no attribute '__exit__'
2016-07-19 12:47:44,363 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!
```

**Comment by goldmann** [comment] 2016-07-19 13:07
Ah, python 2.6. There we go. This tool wasn't tested on such old Python, this may be the issue.

**Comment by goldmann** [comment] 2016-07-20 08:10
I was able to reproduce it with Python 2.6. Unfortunately there is no plan to support such old version. It was EOL'ed in October 2013. We support Python 2.7 or newer. We run our tests on 2.7, 3.4 and 3.5 currently as you can see here: https://github.com/goldmann/docker-squash/blob/e40565b317bff498590c54a897c46438799838a3/tox.ini#L2.

Unfortunately I need to close this issue. Please upgrade to new Python.

**Closed by goldmann** 2016-07-20 08:10 UTC

**Comment by Ehekatl** [comment] 2016-07-20 08:13
@goldmann oh thx man, just fix the version problem today, we are actually not using python2.6 as well, just a bug in our provision tool, now it's working fine, really nice tool you made

**Comment by goldmann** [comment] 2016-07-20 08:17
Awesome news and thanks!
