### ISSUE TITLE
Squashing image with number only id

### ISSUE THREAD

**Issue by gamma** [goldmann/docker-squash#189] opened 2019-11-15 08:28 UTC
I have an image being squashed that starts with an -f "ID'" parameter where the `ID` is a numbers only value. The error then is:

Cannot squash `ID` layers, the `Image Name` image contains only 32 layers.

**Comment by goldmann** [comment] 2019-11-15 08:33
Right, the issue is that the `-f` parameter can take two types of values:

1. Integers - then the number of layers is selected to squash.
2. Alphanumeric - where you specify the layer name (ID/image name).

If it can be parsed as integer, it is assumed that you specify number of layers. I don't think this can be easily changed with out breaking backwards compatibility.

Can you give me an example of such `ID`? Is this the layer ID in fact?

**Comment by gamma** [comment] 2019-11-15 08:37
Yep, the layer ID is "230765370677" - it is by pure chance I hit this. I already thought it could behave in the way you described but I have not found a hint in the documentation about it.

I guess I can rework my method to squash images in my use case though.

It would be nice to have another optional parameter for the number of layers to squash instead of using the "--from" param.

**Comment by goldmann** [comment] 2019-11-15 08:41
At the time when I wrote it it was a superb idea though! I think you should try to play lotto, because it is a fairly small chance to hit this again... 😀

Here is the code:

https://github.com/goldmann/docker-squash/blob/155b6453e85fc6f6cd319fbc510f264982364e9e/docker_squash/image.py#L172-L187

**Comment by gamma** [comment] 2019-11-15 08:45
🤣guess what: I won Lotto 8 times in a row in september (very, very small amounts though)

Anyway: I guess we can consider this issue closed. Could you still please update the documentation?

**Comment by goldmann** [comment] 2019-11-15 08:48
> :rofl: guess what: I won Lotto 8 times in a row in september (very, very small amounts though)

Haha, good one!

> Anyway: I guess we can consider this issue closed. Could you still please update the documentation?

Let's not close it. I'll update CLI help and reference this ticket in fix.

**Comment by goldmann** [comment] 2019-11-15 09:33
@gamma How about this? #190.

**Comment by gamma** [comment] 2020-06-16 20:15
Should be closed now, I guess?

**Closed** 2020-06-17 04:42 UTC
