### ISSUE TITLE
docker-squash is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option

### ISSUE THREAD

**Issue by benchonaut** [goldmann/docker-squash#221] opened 2023-03-21 02:17 UTC
Error message says it all 

```
#87 31.13 Installing collected packages: docker-squash
#87 31.14   DEPRECATION: docker-squash is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

**Comment by rnc** [comment] 2024-02-15 07:57
I am unable to reproduce this on Fedora or Ubunutu. Can you please provide more details on your system, what was installed, and how you provoked the error.

**Comment by rnc** [comment] 2024-02-28 08:43
I'm closing this ; please reopen if you can provide more diagnostics.

**Closed by rnc** 2024-02-28 08:43 UTC
