### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 4: invalid start byte

### ISSUE THREAD

**Issue by Firstyear** [goldmann/docker-squash#86] opened 2016-04-08 05:48 UTC
```
Namespace(development=False, from_layer='10', image='centos_389ds-devel:7', output_path=None, tag='centos_389ds-devel:7', tmp_dir='/var/tmp/docker-squash', verbose=False)
2016-04-08 15:43:31,557 root         INFO     docker-squash version 1.0.0rc3, Docker c6607d2/1.9.1, API 1.21...
2016-04-08 15:43:31,558 root         INFO     Using v1 image format
2016-04-08 15:43:31,576 root         INFO     Old image has 47 layers
2016-04-08 15:43:31,577 root         INFO     Checking if squashing is necessary...
2016-04-08 15:43:31,577 root         INFO     Attempting to squash last 10 layers...
2016-04-08 15:43:31,577 root         INFO     Saving image 06cb1d8580a1a963b3b2f2b03f2f785dbb77a6ead6180623aeba023f615dfa42 to /var/tmp/docker-squash/old/image.tar file...
2016-04-08 15:44:53,820 root         INFO     Image saved!
2016-04-08 15:44:53,988 root         INFO     Unpacking /var/tmp/docker-squash/old/image.tar tar file to /var/tmp/docker-squash/old directory
2016-04-08 15:45:25,632 root         INFO     Archive unpacked!
2016-04-08 15:45:27,063 root         INFO     Squashing image 'centos_389ds-devel:7'...
2016-04-08 15:45:27,704 root         INFO     Starting squashing...
2016-04-08 15:45:27,704 root         INFO     Squashing file '/var/tmp/docker-squash/old/06cb1d8580a1a963b3b2f2b03f2f785dbb77a6ead6180623aeba023f615dfa42/layer.tar'...
2016-04-08 15:45:27,704 root         INFO     Squashing file '/var/tmp/docker-squash/old/cde959e2559849c963b8a05a5d4a6e9507a6f8d9c83b55d567c42f786d9220ab/layer.tar'...
2016-04-08 15:45:27,705 root         INFO     Squashing file '/var/tmp/docker-squash/old/6f82a5ee693948bfa4064e9d53323754f2aef8b7cc91707198a8f8ca15d631a7/layer.tar'...
2016-04-08 15:45:27,705 root         INFO     Squashing file '/var/tmp/docker-squash/old/6a19194783f23003995c1398c4031b7ed8fb58612bf647d90e791d2f710fb0bc/layer.tar'...
2016-04-08 15:45:27,705 root         INFO     Squashing file '/var/tmp/docker-squash/old/07e979eb100f98e3620d9f0a3233c26e52eba84f4135f3a1f9e9014189f5d40e/layer.tar'...
2016-04-08 15:45:27,706 root         INFO     Squashing file '/var/tmp/docker-squash/old/27554522b95b0d19024907812cdb6715cdedb8809187b6fc1495071767dedead/layer.tar'...
2016-04-08 15:45:27,707 root         INFO     Squashing file '/var/tmp/docker-squash/old/e0c86805f8d63dbe1e5f94bcbff2d849269faf0ad61b3f16e13a0153ae86d7f4/layer.tar'...
2016-04-08 15:45:27,707 root         INFO     Squashing file '/var/tmp/docker-squash/old/6ff78ab9e6e18a2ed60a5e5d808461556b19a73e895d86eb05c85b892968ad2b/layer.tar'...
2016-04-08 15:45:27,708 root         INFO     Squashing file '/var/tmp/docker-squash/old/a5d3351f4708b274405e18d851e44ba8ce009cc29a8933d91c15c6b814fb0d62/layer.tar'...
2016-04-08 15:45:27,708 root         INFO     Squashing file '/var/tmp/docker-squash/old/46ca76e33c13bc36439bb20d161ed6cec71a32eb0d7fb9a0b85a3701827fdd9f/layer.tar'...
Traceback (most recent call last):
  File "/bin/docker-squash", line 9, in <module>
    load_entry_point('docker-squash==1.0.0rc3', 'console_scripts', 'docker-squash')()
  File "/usr/lib/python2.7/site-packages/docker_squash/cli.py", line 82, in run
    cli.run()
  File "/usr/lib/python2.7/site-packages/docker_squash/cli.py", line 63, in run
    from_layer=args.from_layer, tag=args.tag, output_path=args.output_path, tmp_dir=args.tmp_dir, development=args.development).run()
  File "/usr/lib/python2.7/site-packages/docker_squash/squash.py", line 61, in run
    return self.squash(image)
  File "/usr/lib/python2.7/site-packages/docker_squash/squash.py", line 73, in squash
    new_image_id = image.squash()
  File "/usr/lib/python2.7/site-packages/docker_squash/image.py", line 67, in squash
    ret = self._squash()
  File "/usr/lib/python2.7/site-packages/docker_squash/v1_image.py", line 32, in _squash
    self._squash_layers(self.layers_to_squash, self.layers_to_move)
  File "/usr/lib/python2.7/site-packages/docker_squash/image.py", line 565, in _squash_layers
    layers_to_move, self.old_image_dir)
  File "/usr/lib/python2.7/site-packages/docker_squash/image.py", line 241, in _files_in_layers
    files[layer] = tar.getnames()
  File "/usr/lib64/python2.7/tarfile.py", line 1838, in getnames
    return [tarinfo.name for tarinfo in self.getmembers()]
  File "/usr/lib64/python2.7/tarfile.py", line 1830, in getmembers
    self._load()        # all members, we first have to
  File "/usr/lib64/python2.7/tarfile.py", line 2405, in _load
    tarinfo = self.next()
  File "/usr/lib64/python2.7/tarfile.py", line 2344, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib64/python2.7/tarfile.py", line 1248, in fromtarfile
    return obj._proc_member(tarfile)
  File "/usr/lib64/python2.7/tarfile.py", line 1270, in _proc_member
    return self._proc_pax(tarfile)
  File "/usr/lib64/python2.7/tarfile.py", line 1400, in _proc_pax
    value = value.decode("utf8")
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 4: invalid start byte
```

**Comment by goldmann** [comment] 2016-04-08 07:26
Thanks for report.

This is a duplicate of #76 which is already solved in master. It'll be part of 1.0.0rc4 release (hopefully today), but you are free to use master.

Closing.

**Closed by goldmann** 2016-04-08 07:26 UTC
