### ISSUE TITLE
Sconification failed  : [Errno 2] No such file or directory: '/tmp/docker-squash-vagger9i/old/blobs/layer.tar

### ISSUE THREAD

**Issue by raorla** [goldmann/docker-squash#237] opened 2024-02-05 12:28 UTC
ERROR: Error while squashing image XXXtee-scone-hello-world:1.0.0-debug: 2024-02-05 12:24:10,602 root         INFO     docker-squash version 1.0.9, Docker fce6e0c, API 1.44...
2024-02-05 12:24:10,603 root         INFO     Using v2 image format
2024-02-05 12:24:10,609 root         INFO     Old image has 16 layers
2024-02-05 12:24:10,609 root         INFO     Checking if squashing is necessary...
2024-02-05 12:24:10,609 root         INFO     Attempting to squash last 16 layers...
2024-02-05 12:24:10,610 root         INFO     Saving image sha256:74d6a53a4cf8364746fb357a0e44c8d8f0c2243953747a5d1716adb624a52527 to /tmp/docker-squash-vagger9i/old directory...
2024-02-05 12:24:14,230 root         INFO     Image saved!
2024-02-05 12:24:14,230 root         INFO     Squashing image 'raorla/tee-scone-hello-world:1.0.0-debug'...
2024-02-05 12:24:14,231 root         INFO     Starting squashing...
2024-02-05 12:24:14,231 root         INFO     Squashing file '/tmp/docker-squash-vagger9i/old/blobs/layer.tar'...
2024-02-05 12:24:14,253 root         ERROR    [Errno 2] No such file or directory: '/tmp/docker-squash-vagger9i/old/blobs/layer.tar'
2024-02-05 12:24:14,253 root         ERROR    Execution failed, consult logs above. If you think this is our fault

**Comment by rnc** [comment] 2024-02-05 14:27
Duplicate of #236

**Closed by rnc** 2024-02-05 14:27 UTC
