### ISSUE TITLE
"Not a directory" issue

### ISSUE THREAD

**Issue by mgzenitech** [goldmann/docker-squash#223] opened 2023-04-28 12:15 UTC
For some reason, it is impossible to squash anything on my pc:
```python
from logging import getLogger
from docker_squash.squash import Squash

image_name: str = "xxx"
tag: str = "yyy"

Squash(log = getLogger(), image = f"{image_name}:{tag}", tag = f"{image_name}:{tag}-compressed").run()
```

Dies with:
```
Traceback (most recent call last):
  File "<stdin>", line 66, in <module>
  File "/home/xxx/Documents/Projects/docker-internal-images/.venv/lib/python3.10/site-packages/docker_squash/squash.py", line 62, in run
    return self.squash(image)
  File "/home/xxx/Documents/Projects/docker-internal-images/.venv/lib/python3.10/site-packages/docker_squash/squash.py", line 92, in squash
    new_image_id=image.squash()
  File "/home/xxx/Documents/Projects/docker-internal-images/.venv/lib/python3.10/site-packages/docker_squash/image.py", line 75, in squash
    ret = self._squash()
  File "/home/xxx/Documents/Projects/docker-internal-images/.venv/lib/python3.10/site-packages/docker_squash/v2_image.py", line 39, in _squash
    self._squash_layers(self.layer_paths_to_squash,
  File "/home/xxx/Documents/Projects/docker-internal-images/.venv/lib/python3.10/site-packages/docker_squash/image.py", line 727, in _squash_layers
    with tarfile.open(layer_tar_file, 'r', format=tarfile.PAX_FORMAT) as layer_tar:
  File "/home/xxx/.pyenv/versions/3.10.8/lib/python3.10/tarfile.py", line 1632, in open
    return func(name, "r", fileobj, **kwargs)
  File "/home/xxx/.pyenv/versions/3.10.8/lib/python3.10/tarfile.py", line 1698, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/home/xxx/.pyenv/versions/3.10.8/lib/python3.10/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
NotADirectoryError: [Errno 20] Not a directory: '/tmp/docker-squash-lyjq6e8d/old/626512d3e5a884971d72806e669a7079484e7bac53e4e3521b65c550ce35a148.tar/layer.tar'
```

**Comment by rnc** [comment] 2023-05-19 15:11
Can you run with debug logging and with the newest version (1.1.0) of docker-squash? What happens if you run via the CLI?

**Comment by rnc** [comment] 2024-02-05 14:30
Turns out this is likely a duplicate of #236

**Closed by rnc** 2024-02-05 14:30 UTC
