### ISSUE TITLE
Incorrect logic for symlinks

### ISSUE THREAD

**Issue by phpdude** [goldmann/docker-squash#111] opened 2016-07-27 15:12 UTC
Please check commit https://github.com/goldmann/docker-squash/commit/afd81aefb5230ef8f001fec544e8649984427444

It is not correct, because you are checking for symlinks' targets in the list `squashed_files` (`member.linkname not in squashed_files`) which CAN BE NOT FILLED YET FOR TARGET FILES. This is incorrect.

You need to add symlinks to a temporary list and iterate through them after processing ALL other type of members in `layer_tar`, this will avoid the critical bug you created in the commit :)

Do you need a help in resolving the issue?

**Comment by goldmann** [comment] 2016-07-28 08:39
That's a pretty good finding. You are most probably right. This needs to be fixed. First we need to find a reproducer for this issue and write an integration test that will fail. Later we can do the same as with hard links. Should be easy to fix, but first I would like to have a reproducer as I said.

**Comment by phpdude** [comment] 2016-07-28 08:44
I will try to create file for you now, because I have the issue on a real project. So it will be easy, I just need to "extract" part of a folders tree.

**Comment by goldmann** [comment] 2016-07-28 08:47
Ah, cool, I'll work on a fix in meantime.

**Comment by phpdude** [comment] 2016-07-28 09:22
Ok, I did it :)

``` python
    def test_correct_symlinks_squashing(self):
        dockerfile = '''
        FROM %s
        RUN mkdir -p /zzz
        RUN ln -s /zzz /xxx
        ''' % TestIntegSquash.BUSYBOX_IMAGE

        with self.Image(dockerfile) as image:
            with self.SquashedImage(image) as squashed_image:
                squashed_image.assertFileExists('zzz')
                squashed_image.assertFileExists('xxx')

                with self.Container(squashed_image) as container:
                    container.assertFileExists('zzz')
                    container.assertFileExists('xxx')
```

**Comment by phpdude** [comment] 2016-07-28 09:23
Now it fails in master branch :)

**Comment by goldmann** [comment] 2016-07-28 09:27
I can confirm this, working on a fix now.

**Comment by phpdude** [comment] 2016-07-28 09:39
Also, what about make the "symlinks processing" feature configurable? I think we must allow a user skip the processing because sometimes a user can "symlinking" to a mounted path (which will exist only on a container start) if we will remove a link from an image he will not be able to do this :)

I think a simple flag to disable links processing feature will be enough.

**Comment by goldmann** [comment] 2016-07-28 09:41
We could probably see which symlinks and not bound and mark them to add them anyway. In fact I was just about to write similar comment highlighting this issue :)

**Comment by phpdude** [comment] 2016-07-28 09:44
@goldmann we can (or remove without flags and mark with flag). What does a marking? Something like a "warning" on squashing logs? I don't remember any marks, maybe I didn't use them yet :)

**Comment by goldmann** [comment] 2016-07-28 09:48
No, I mean in the code - when processing a symlink that  does not have a target in place - "mark" it and remember to add it later either case. This should be doable since we already generate a list of files in each layer, even for these we move (and this is required to see if the target exists).

**Comment by phpdude** [comment] 2016-07-28 09:53
Ah, yeah, it looks like a good idea. Sorry, I don't know internals so deep, I only understand how it must work :)

Yes, it would be nice to be able to add a symlink to future paths (because it makes a lot of problems to a user if he created a symlink and didn't find it at the end :D).

**Comment by goldmann** [comment] 2016-07-28 12:19
It seems I have a fix for this bug report. Let's divide these issues into two: this - to make it work as expected, 2nd - to add back symbolic links that were "broken" in first place, I'll create a ticket for this.

**Comment by goldmann** [comment] 2016-07-28 12:21
Created #112 to track the 2nd issue.

**Comment by goldmann** [comment] 2016-07-28 12:42
Sent a PR, can you give the `gh-111-symlinks` branch a shot?

**Comment by phpdude** [comment] 2016-07-28 14:40
Hi again, I was away from keyboard. Do you need something from me? Do you want for something from me?

**Comment by goldmann** [comment] 2016-07-28 14:41
See comment above ;)

**Closed** 2016-07-29 14:29 UTC
Labels: bug, high priority

**Comment by goldmann** [comment] 2016-07-29 14:31
The PR was merged and this issue was closed. Please try with latest master and reopen if you still see the issue.
